name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker Image
      run: docker build -t nospof/terragrunt:${{ github.sha }} .
    - name: docker tag
      run: docker tag  nospof/terragrunt:${{ github.sha }} nospof/terragrunt:latest
    - name: docker login
      run : docker login -u ${{ secrets.dockerUsername }} -p ${{ secrets.dockerPassword }}
    - name: docker push
      run: docker push nospof/terragrunt:${{ github.sha }}
    - name: docker push latest
      run: docker push nospof/terragrunt:latest